/** 统一标签类型（武器/效果/分类） */
export type Tag =
    | 'qi' // 炁
    | 'slash' // 劈砍
    | 'blunt' // 钝击
    | 'pierce' // 戳刺
    | 'parry' // 可招架
    | 'imperial' // 御物
    | 'stagger' // 失衡
    | 'paralyze' // 麻痹
    | 'burn' // 灼烧
    | 'poison' // 中毒
    | 'interrupt' // 打断
    | 'stun' // 眩晕
    | 'cleanse' // 净化
    | 'bleed' // 流血
    | 'counter' // 反击
    | 'ignore_parry' // 无视招架
    | 'fixed_damage' // 固定伤害
    | 'self_damage' // 自伤
    | 'knockback' // 击退
    | 'cripple' // 崩劲
    | 'implant' // 义体
    | 'heal' // 回复
    | 'buff' // 增益
    | 'trigger' // 触发
    | 'talent' // 天赋
    | 'passive' // 功法
    | 'frost' // 霜冻
    | 'sand_blind' // 迷眼
    | 'knockdown' // 倒地
