/** 统一标签类型（武器/效果/分类） */
export type Tag =
    | 'qi'
    | 'slash'
    | 'blunt'
    | 'pierce'
    | 'parry'
    | 'imperial'
    | 'stagger'
    | 'paralyze'
    | 'poison'
    | 'interrupt'
    | 'stun'
    | 'cleanse'
    | 'bleed'
    | 'counter'
    | 'ignore_parry'
    | 'fixed_damage'
    | 'self_damage'
    | 'knockback'
    | 'cripple'
    | 'implant'
    | 'heal'
    | 'buff'
