/** 统一标签类型（武器/效果/分类） */
export type Tag =
    | 'qi' // 炁
    | 'slash' // 劈砍
    | 'blunt' // 钝击
    | 'pierce' // 戳刺
    | 'parry' // 可招架
    | 'imperial' // 御物
    | 'stagger' // 失衡
    | 'paralyze' // 麻痹
    | 'burn' // 灼烧
    | 'poison' // 中毒
    | 'interrupt' // 打断
    | 'stun' // 眩晕
    | 'cleanse' // 净化
    | 'bleed' // 流血
    | 'counter' // 反击
    | 'ignore_parry' // 无视招架
    | 'fixed_damage' // 固定伤害
    | 'self_damage' // 自伤
    | 'knockback' // 击退
    | 'cripple' // 崩劲
    | 'implant' // 义体
    | 'heal' // 回复
    | 'buff' // 增益
    | 'electric' // 雷电
    | 'trigger' // 触发
    | 'talent' // 天赋
    | 'passive' // 功法
    | 'frost' // 霜冻
    | 'polearm' // 长柄
    | 'heavy' // 巨型双手
    | 'sand_blind' // 迷眼
    | 'knockdown' // 倒地    | 'support' // 辅助（buff/回复，不攻击）
    | 'move' // 位移
    | 'range' // 远程
    | 'counter' // 反击
    // | 'charge' // 冲锋
    | 'defense' // 防御
    | 'debuff' // 弱化
    | 'dot' // 持续伤害
    | 'melee' // 近战武器
    | 'damage' // 伤害增强
    | 'summon' // 召唤相关
    | 'stance' // 架势/姿态
    | 'support' // 辅助
    | 'retrieve_weapon' // 收回武器
    | 'bonus_damage' // 独立附加伤害
    | 'dual_wield' // 双持
    | 'range_up' // 增加攻击范围
    | 'inherent' // 固有（不可复制、不可禁用）
    | 'weapon' // 武器来源的 buff
