import type { Tag } from '../engine/entities/tag'

/** Tag → 中文显示名 */
export const TAG_CN: Record<Tag, string> = {
    qi: '炁',
    slash: '劈砍',
    unarmed: '拳脚',
    blunt: '钝击',
    pierce: '戳刺',
    parry: '招架',
    internal: '内置',
    imperial: '御物',
    paralyze: '麻痹',
    burn: '灼烧',
    poison: '中毒',
    stun: '眩晕',
    cleanse: '净化',
    bleed: '流血',
    counter: '反击',
    ignore_parry: '破招',
    self_damage: '自伤',
    knockback: '击退',
    implant: '义体',
    heal: '回复',
    buff: '增益',
    electric: '雷电',
    trigger: '触发',
    talent: '天赋',
    frost: '霜冻',
    sand_blind: '迷眼',
    knockdown: '倒地',
    pre_action: '前置',
    post_action: '后置',
    move: '位移',
    range: '远程',
    defense: '防御',
    debuff: '弱化',
    melee: '近战',
    one_handed: '单手',
    two_handed: '双手',
    summon: '召唤',
    stance: '架势',
    polearm: '长柄',
    heavy: '重型',
    heavy_reduce: '化解',
    retrieve_weapon: '收回武器',
    bonus_damage: '附伤',
    range_up: '射程',
    inherent: '特性',
    weapon: '武器',
    thrown: '暗器',
    super_armor: '罡体',
    jiu: '酒',
    craft: '天工',
    qi_action: '炁招',
    chan: '缠劲',
    low_hp: '残血',
}

/** Tag → 两套主题的徽章颜色（文字 + 描边）。色位见 docs/ui-color-system.md 第 7 节 */
export const TAG_COLOR: Record<Tag, { light: string; dark: string }> = {
    qi: { light: '#004361', dark: '#3285a2' },
    unarmed: { light: '#3c6e67', dark: '#8abdb6' },
    slash: { light: '#3c6e67', dark: '#8abdb6' },
    blunt: { light: '#3b6c75', dark: '#88bbc4' },
    pierce: { light: '#3b6c75', dark: '#88bbc4' },
    parry: { light: '#8c4971', dark: '#d79dbd' },
    imperial: { light: '#3b6c75', dark: '#88bbc4' },
    paralyze: { light: '#664700', dark: '#aa8e53' },
    burn: { light: '#8a5800', dark: '#d0ac5f' },
    poison: { light: '#214502', dark: '#63864f' },
    stun: { light: '#61655f', dark: '#aeb3ac' },
    cleanse: { light: '#3a7b5b', dark: '#83c1a0' },
    bleed: { light: '#b32228', dark: '#f4928a' },
    counter: { light: '#954755', dark: '#df9ca5' },
    ignore_parry: { light: '#8c4971', dark: '#d79dbd' },
    self_damage: { light: '#9b424d', dark: '#e9979d' },
    knockback: { light: '#383c37', dark: '#787c76' },
    implant: { light: '#3d3d02', dark: '#7c7e54' },
    heal: { light: '#3a7b5b', dark: '#83c1a0' },
    buff: { light: '#3a7b5b', dark: '#83c1a0' },
    electric: { light: '#4d57b7', dark: '#a1b1ff' },
    trigger: { light: '#3d3d02', dark: '#7c7e54' },
    talent: { light: '#3d3d02', dark: '#7c7e54' },
    frost: { light: '#655e7d', dark: '#bfb9d8' },
    polearm: { light: '#3b6c75', dark: '#88bbc4' },
    heavy: { light: '#3b6c75', dark: '#88bbc4' },
    heavy_reduce: { light: '#8c4971', dark: '#d79dbd' },
    sand_blind: { light: '#61655f', dark: '#aeb3ac' },
    knockdown: { light: '#383c37', dark: '#787c76' },
    pre_action: { light: '#3d3d02', dark: '#7c7e54' },
    post_action: { light: '#3d3d02', dark: '#7c7e54' },
    move: { light: '#804b8c', dark: '#ce9cd9' },
    range: { light: '#3b6c75', dark: '#88bbc4' },
    internal: { light: '#3d3d02', dark: '#7c7e54' },
    defense: { light: '#954755', dark: '#df9ca5' },
    debuff: { light: '#61655f', dark: '#aeb3ac' },
    melee: { light: '#3b6c75', dark: '#88bbc4' },
    one_handed: { light: '#3c6e67', dark: '#8abdb6' },
    two_handed: { light: '#3b6c75', dark: '#88bbc4' },
    summon: { light: '#3d3d02', dark: '#7c7e54' },
    stance: { light: '#3d3d02', dark: '#7c7e54' },
    retrieve_weapon: { light: '#3d3d02', dark: '#7c7e54' },
    bonus_damage: { light: '#9b424d', dark: '#e9979d' },
    range_up: { light: '#3d3d02', dark: '#7c7e54' },
    inherent: { light: '#3d3d02', dark: '#7c7e54' },
    weapon: { light: '#3c6e67', dark: '#8abdb6' },
    thrown: { light: '#3c6e67', dark: '#8abdb6' },
    super_armor: { light: '#954755', dark: '#df9ca5' },
    jiu: { light: '#7b5c43', dark: '#caaa92' },
    craft: { light: '#3d3d02', dark: '#7c7e54' },
    qi_action: { light: '#32669a', dark: '#85b6e9' },
    chan: { light: '#32669a', dark: '#85b6e9' },
    low_hp: { light: '#681f00', dark: '#ab6646' },
};
